
# tasks file for apache2
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
