# file: mysql/tasks/users.yml

- name: MySQL | Make sure the MySQL users are present
  mysql_user:
    login_user: root
    login_password: "{{mysql_root_password}}"
    name: "{{item.name}}"
    password: "{{item.pass | default('pass')}}"
    priv: "{{item.priv | default('*.*:ALL')}}"
    state: present
    host: "{{item.host | default('localhost')}}"
  with_items: "{{mysql_users}}"
  when: mysql_users|length > 0
